"""Create table bird

Revision ID: 427b4b426b3f
Revises: 
Create Date: 2023-06-29 11:51:42.041624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427b4b426b3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birds')
    # ### end Alembic commands ###
